#!/usr/bin/env node
const args = process.argv.slice(2)

if (args.length !== 2) {
  console.error("Usage: sync <DIRECTORY> <BUCKET>")
  process.exit(64)
}

const root = args[0]
const bucket = args[1]

const awsS3Sync = require('@akud/aws-s3-sync-by-hash');

awsS3Sync({
 bucket,
 root,
 force: false,
 delete: true
});
