name: ops
version: 0.0.0.1
license: MIT

dependencies:
  - base
  - rio

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - amazonka
    - amazonka-autoscaling
    - amazonka-ecs
    - amazonka-sqs
    - bytestring
    - http-conduit
    - http-types
    - lens
    - lens-aeson
    - load-env
    - optparse-applicative
    - parsec
    - random

executables:
  agent:
    main: Main.hs
    source-dirs: agent
    dependencies:
      - ops

# tests:
#   doctest:
#     main: Main.hs
#     source-dirs: doctest
#     dependencies:
#       - doctest
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     dependencies:
#       - hspec
#       - ops
