name: hooks
version: 0.0.0.0

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base >=4.7 && <5

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - http-types
    - process
    - scotty
    - text

executables:
  hooks:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hooks
