---
name: restyled-ops
version: "0.0.0"

# Dependencies shared in *all* targets
dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - aeson
    - aeson-qq
    - amazonka
    - amazonka-cloudformation
    - amazonka-core
    - async
    - bytestring
    - containers
    - escaped
    - lens
    - optparse-applicative
    - pushover
    - safe
    - safe-exceptions
    - stratosphere
    - text
    - time

executables:
  restyled-ops:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - restyled-ops
      - text

tests:
  doctest:
    main: DocTest.hs
    dependencies:
      - doctest
