StackName: prod-log-forwarder
Template: serverless.yaml
Parameters:
  - Name: Environment
    Value: prod

  - Name: FunctionName
    Value: global-log-forwarder
  - Name: FunctionSourceKey
    Value: logdna-cloudwatch.zip
  - Name: FunctionRuntime
    Value: nodejs10.x
  - Name: FunctionHandler
    Value: index.handler

  - Name: LogInvocation
    Value: "True"

  - Name: Version
    Value: 1
Tags:
  - Key: Environment
    Value: prod
