StackName: prod-ops
Template: ops.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: QueueAlertThreshold
    Value: 200

  # Increment to deploy a template-only change
  - Name: Version
    Value: 6
