StackName: prod-record-metrics
Template: serverless.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: FunctionName
    Value: record-metrics
  - Name: FunctionSourceKey
    Value: record-metrics.zip
  - Name: ScheduleExpression
    Value: rate(1 minute)
Tags:
  - Key: Environment
    Value: prod

# Increment to deploy template-only changes: v1
