StackName: prod-machines
Template: restyle-machines.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: InstanceAmi
    Value: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  - Name: InstanceKeyPair
    Value: patrick@leo
  - Name: RestyledHost
    Value: https://restyled.io
  - Name: DesiredCapacity
    Value: 1
  - Name: ScaleUpThreshold
    Value: 30
  - Name: ScaleUpCapacity
    Value: 6
  - Name: AgentVersion
    Value: 1.1.0
  - Name: UserDataVersion
    Value: 1.0.2
Tags:
  - Key: Environment
    Value: prod

# Increment to deploy template-only changes: v0
