StackName: prod-ops
Template: ops.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: QueueAlertThreshold
    Value: 200
Tags:
  - Key: Environment
    Value: prod

# Increment to deploy template-only changes: v0
