StackName: prod-check-redis-url
Template: serverless.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: FunctionName
    Value: check-redis
  - Name: FunctionSourceKey
    Value: src/check-redis-url/8dfc497553e5a65802a6c1b8fb3d5659822ffdc5.zip
  - Name: FunctionRuntime
    Value: nodejs10.x
  - Name: FunctionHandler
    Value: index.handler
  - Name: FunctionRole
    Value: check-redis-url
  - Name: ScheduleExpression
    Value: rate(2 minutes)
Tags:
  - Key: Environment
    Value: prod

# Increment to deploy template-only changes: v0
