StackName: prod-sync-marketplace
Template: fargate-backend.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: Name
    Value: sync-marketplace
  - Name: Subcommand
    Value: sync-marketplace
  - Name: Approot
    Value: https://restyled.io
  - Name: ScheduleExpression
    Value: rate(5 minutes)
  - Name: RestyledImage
    Value: restyled/restyled.io:264410b
  - Name: RestylerImage
    Value: restyled/restyler:88bfc25
Tags:
  - Key: Environment
    Value: prod
  - Key: App
    Value: sync-marketplace

# Increment to deploy template-only changes: v1
