StackName: prod-vpc
Template: vpc.yaml
Parameters:
  - Name: Environment
    Value: prod
  - Name: CidrBlock
    Value: 172.31.0.0/16
  - Name: Subnet1CidrBlock
    Value: 172.31.32.0/20
  - Name: Subnet2CidrBlock
    Value: 172.31.16.0/20
  - Name: Subnet3CidrBlock
    Value: 172.31.64.0/20
Tags:
  - Key: Environment
    Value: prod

# Increment to deploy template-only changes: v0
