Parameters:
  Environment:
    Type: String

  Version:
    Type: Number
    Default: 0

Outputs:
  Version:
    Description: "Template version"
    Value: !Ref Version

Resources:
  GetParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Get SSM Parameters under /restyled/${Environment}"
      ManagedPolicyName: !Sub "restyled-${Environment}-get-parameter"
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": "ssm:GetParameter",
            "Resource": [
              "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restyled/${Environment}/*"
            ]
          }]
        }

  RedisUrlPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Full access to SSM Parameter /restyled/${Environment}/redis-url"
      ManagedPolicyName: !Sub "restyled-${Environment}-redis-url"
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": "ssm:*",
            "Resource": [
              "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restyled/${Environment}/redis-url"
            ]
          }]
        }

  StoreCloudWatchLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Store CloudWatch Logs
      ManagedPolicyName: !Sub "restyled-${Environment}-store-cloudwatch-logs"
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": [
              "arn:aws:logs:*:*:*"
            ]
          }]
        }

  CloudWatchMetricsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Full access to CloudWatch Metrics
      ManagedPolicyName: !Sub "restyled-${Environment}-cloudwatch-metrics"
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": [
              "cloudwatch:ListMetrics",
              "cloudwatch:GetMetric*",
              "cloudwatch:PutMetric*"
            ],
            "Resource": "*"
          }]
        }

  SNSPublishPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Publish to any ${Environment} SNS Topic"
      ManagedPolicyName: !Sub "restyled-${Environment}-sns-publish"
      PolicyDocument: |
        {
           "Version": "2012-10-17",
           "Statement": [{
              "Effect": "Allow",
              "Action": ["sns:Publish"],
              "Resource": "*"
           }]
        }

  MachinesSQSAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Full access to restyled-${Environment}-machines SQS"
      ManagedPolicyName: !Sub "restyled-${Environment}-machines-sqs"
      PolicyDocument: !Sub |
        {
           "Version": "2012-10-17",
           "Statement": [{
              "Effect": "Allow",
              "Action": ["sqs:*"],
              "Resource": [
                "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-machines-*"
              ]
           }]
        }

  LifecycleActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Completing ASG Lifecycle actions
      ManagedPolicyName: !Sub "restyled-${Environment}-complete-lifecycle-action"
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": "autoscaling:CompleteLifecycleAction",
            "Resource": "*"
          }]
        }

  MachinesAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Auto-scaling Role for ${Environment}"
      RoleName: !Sub "restyled-${Environment}-auto-scaling"
      AssumeRolePolicyDocument: |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "autoscaling.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - !Ref LifecycleActionsPolicy
        - !Ref MachinesSQSAccessPolicy
        - !Ref SNSPublishPolicy

  MachinesInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Auto-scaling Instance Role for ${Environment}"
      RoleName: !Sub "restyled-${Environment}-machine"
      AssumeRolePolicyDocument: |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - !Ref GetParameterPolicy
        - !Ref LifecycleActionsPolicy
        - !Ref MachinesSQSAccessPolicy
        - !Ref SNSPublishPolicy
        - !Ref StoreCloudWatchLogsPolicy

  MachinesInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "restyled-${Environment}-machine"
      Roles:
        - !Ref MachinesInstanceRole

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Execution role for ${Environment} Lambdas"
      RoleName: !Sub "restyled-${Environment}-lambda-execution"
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "edgelambda.amazonaws.com",
                "lambda.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }]
        }

      ManagedPolicyArns:
        - !Ref CloudWatchMetricsPolicy
        - !Ref GetParameterPolicy
        - !Ref StoreCloudWatchLogsPolicy

  # Special-purpose, because it needs write to SSM
  CheckRedisUrlExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Execution role for ${Environment} check-redis-url"
      RoleName: !Sub "restyled-${Environment}-check-redis-url"
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "edgelambda.amazonaws.com",
                "lambda.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }]
        }

      ManagedPolicyArns:
        - !Ref CloudWatchMetricsPolicy
        - !Ref GetParameterPolicy
        - !Ref StoreCloudWatchLogsPolicy
        - !Ref RedisUrlPolicy
