Parameters:
  # Unused. Only present to increment in the stacks definition to trigger a
  # deploy when it's a template-only change.
  Version:
    Type: Number
    Default: 0
  Environment:
    Type: String
  QueueScaleUpThreshold:
    Type: Number
  QueueAlertThreshold:
    Type: Number

Resources:
  GetRestyledApiKeyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Access Parameter restyled/${Environment}/restyled-api-token"
      PolicyDocument: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [{
              "Effect": "Allow",
              "Action": "ssm:GetParameter",
              "Resource": [
                "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restyled/${Environment}/restyled-api-token"
              ]
            }]
          }
      Roles:
        - !Ref RecordMetricsExecutionRole

  # TODO: centralize this
  StoreCloudWatchLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Store CloudWatch Logs
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": [
              "arn:aws:logs:*:*:*"
            ]
          }]
        }
      Roles:
        - !Ref CheckRedisUrlExecutionRole
        - !Ref RecordMetricsExecutionRole

  CloudWatchMetricsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Full access to CloudWatch Metrics
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Action": [
              "cloudwatch:ListMetrics",
              "cloudwatch:GetMetric*",
              "cloudwatch:PutMetric*"
            ],
            "Resource": "*"
          }]
        }
      Roles:
        - !Ref RecordMetricsExecutionRole

  # Dedicate policy for reading and writing what this Lambda needs specifically
  CheckRedisUrlPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Parameters access for restyled-${Environment}-check-redis-url"
      PolicyDocument: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [{
              "Effect": "Allow",
              "Action": "ssm:*",
              "Resource": [
                "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restyled/${Environment}/redis-url"
              ]
            } , {
              "Effect": "Allow",
              "Action": "ssm:GetParameter",
              "Resource": [
                "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restyled/${Environment}/heroku-api-key"
              ]
            }]
          }
      Roles:
        - !Ref CheckRedisUrlExecutionRole

  CheckRedisUrlExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "edgelambda.amazonaws.com",
                "lambda.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }]
        }

  CheckRedisUrl:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "restyled-${Environment}-check-redis-url"
      Description: |
        Check (and fix) redis-url SSM Parameter

      Runtime: nodejs10.x
      Code:
        S3Bucket: infra.restyled.io
        S3Key: check-redis-url.zip
      Handler: index.handler
      Timeout: 30
      Environment:
        Variables:
          ENV: !Ref Environment
      Role: !GetAtt CheckRedisUrlExecutionRole.Arn

  CheckRedisUrlRule:
    Type: AWS::Events::Rule
    Properties:
      Description: CheckRedisUrl every two minutes
      ScheduleExpression: rate(2 minutes)
      State: "ENABLED"
      Targets:
        - Id: !Sub "restyled-${Environment}-check-redis-url"
          Arn: !GetAtt CheckRedisUrl.Arn

  CheckRedisUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CheckRedisUrl
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CheckRedisUrlRule.Arn

  RecordMetricsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "edgelambda.amazonaws.com",
                "lambda.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }]
        }

  RecordMetrics:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "restyled-${Environment}-record-metrics"
      Description: |
        Record metrics to CloudWatch every minute

      Runtime: python3.8
      Code:
        S3Bucket: infra.restyled.io
        S3Key: record-metrics.zip
      Handler: main.handler
      Timeout: 30
      Environment:
        Variables:
          ENV: !Ref Environment
      Role: !GetAtt RecordMetricsExecutionRole.Arn

  RecordMetricsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Record metrics every minute
      ScheduleExpression: rate(1 minute)
      State: "ENABLED"
      Targets:
        - Id: !Sub "restyled-${Environment}-record-metrics"
          Arn: !GetAtt RecordMetrics.Arn

  RecordMetricsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RecordMetrics
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt RecordMetricsRule.Arn

  AlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "RestyledAlarmsTopic-${Environment}"
      Subscription:
        - Protocol: email
          Endpoint: alarms@restyled.io

  QueueEmptyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Fn::ImportValue: !Sub "${Environment}-machines-ScaleDownPolicy"
        - Fn::ImportValue: !Sub "${Environment}-webhooks-ScaleDownPolicy"
      AlarmDescription: !Sub "Restyled ${Environment} Queue is empty"
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 1
      MetricName: QueueDepth
      Namespace: Restyled
      Period: 60
      Statistic: Maximum
      Threshold: 0
      Unit: Count

  QueueScaleUpAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Fn::ImportValue: !Sub "${Environment}-machines-ScaleUpPolicy"
        - Fn::ImportValue: !Sub "${Environment}-webhooks-ScaleUpPolicy"
      AlarmDescription: !Sub "Restyled ${Environment} Queue is at ScaleUp threshold"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 1
      MetricName: QueueDepth
      Namespace: Restyled
      Period: 60
      Statistic: Minimum
      Threshold: !Ref QueueScaleUpThreshold
      Unit: Count

  QueueAlertAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Queue is at Alert threshold"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 2
      MetricName: QueueDepth
      Namespace: Restyled
      Period: 120
      Statistic: Minimum
      Threshold: !Ref QueueAlertThreshold
      TreatMissingData: breaching
      Unit: Count

  UnknownFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Unknown Failures"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 1
      MetricName: JobsFailedUnknown
      Namespace: Restyled
      Period: 60
      Statistic: Minimum
      Threshold: 5
      TreatMissingData: breaching
      Unit: Count
