Parameters:
  Environment:
    Type: String
  QueueAlertThreshold:
    Type: Number

  Version:
    Type: Number
    Default: 0

Outputs:
  Version:
    Description: "Template version"
    Value: !Ref Version

Resources:
  AlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "RestyledAlarmsTopic-${Environment}"
      Subscription:
        - Protocol: email
          Endpoint: alarms@restyled.io

  QueueAlertAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Queue is at Alert threshold"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 2
      MetricName: QueueDepth
      Namespace: Restyled
      Period: 120
      Statistic: Minimum
      Threshold: !Ref QueueAlertThreshold
      TreatMissingData: breaching
      Unit: Count

  UnknownFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Unknown Failures"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: prod
      EvaluationPeriods: 1
      MetricName: JobsFailedUnknown
      Namespace: Restyled
      Period: 60
      Statistic: Minimum
      Threshold: 5
      TreatMissingData: breaching
      Unit: Count
