Parameters:
  # Unused. Only present to increment in the stacks definition to trigger a
  # deploy when it's a template-only change.
  Version:
    Type: Number
    Default: 0

  Environment:
    Type: String
  FunctionName:
    Type: String
  FunctionSourceKey:
    Type: String

  FunctionSourceBucket:
    Type: String
    Default: infra.restyled.io
  FunctionRuntime:
    Type: String
    Default: python3.8
  FunctionHandler:
    Type: String
    Default: main.handler
  FunctionTimeout:
    Type: Number
    Default: 30

  ScheduleExpression:
    Type: String
    Default: "" # rate(1 minute)

Conditions:
  HasScheduleExpression: !Not [!Equal [!Ref ScheduleExpression, ""]]

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "restyled-${Environment}-${FunctionName}"
      Runtime: !Ref FunctionRuntime
      Code:
        S3Bucket: !Ref FunctionSourceBucket
        S3Key: !Ref FunctionSourceKey
      Handler: !Ref FunctionHandler
      Timeout: !Ref FunctionTimeout
      Environment:
        Variables:
          ENV: !Ref Environment
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "edgelambda.amazonaws.com",
                "lambda.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }]
        }

      ManagedPolicyArns:
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/restyled-${Environment}-cloudwatch-metrics"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/restyled-${Environment}-get-parameter"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/restyled-${Environment}-store-cloudwatch-logs"

  LambdaScheduleRule:
    Condition: HasScheduleExpression
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub "Trigger restyled-${Environment}-${FunctionName}"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Id: !Sub "restyled-${Environment}-${FunctionName}"
          Arn: !GetAtt LambdaFunction.Arn

  LambdaSchedulePermission:
    Condition: HasScheduleExpression
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleRule.Arn
