Parameters:
  Environment:
    Type: String
  FunctionName:
    Type: String
  FunctionSourceKey:
    Type: String

  FunctionSourceBucket:
    Type: String
    Default: infra.restyled.io
  FunctionRuntime:
    Type: String
    Default: python3.8
  FunctionHandler:
    Type: String
    Default: main.handler
  FunctionTimeout:
    Type: Number
    Default: 30

  ScheduleExpression:
    Type: String
    Default: ""

  Version:
    Type: Number
    Default: 0

Outputs:
  Version:
    Description: "Template version"
    Value: !Ref Version

Conditions:
  HasScheduleExpression: !Not [!Equals [!Ref ScheduleExpression, ""]]

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "restyled-${Environment}-${FunctionName}"
      Runtime: !Ref FunctionRuntime
      Code:
        S3Bucket: !Ref FunctionSourceBucket
        S3Key: !Ref FunctionSourceKey
      Handler: !Ref FunctionHandler
      Timeout: !Ref FunctionTimeout
      Environment:
        Variables:
          ENV: !Ref Environment
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/restyled-${Environment}-lambda-execution"

  LambdaScheduleRule:
    Condition: HasScheduleExpression
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub "Trigger restyled-${Environment}-${FunctionName}"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Id: !Sub "restyled-${Environment}-${FunctionName}"
          Arn: !GetAtt LambdaFunction.Arn

  LambdaSchedulePermission:
    Condition: HasScheduleExpression
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleRule.Arn
