Parameters:
  FunctionName:
    Type: String
  FunctionSourceKey:
    Type: String

  FunctionSourceBucket:
    Type: String
    Default: infra.restyled.io
  FunctionRuntime:
    Type: String
  FunctionHandler:
    Type: String
  FunctionTimeout:
    Type: Number
    Default: 30
  FunctionRole:
    Type: String
    Default: "lambda-execution"

  LogForwarding:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "True"
  LogInvocation:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "False"
  ScheduleExpression:
    Type: String
    Default: ""

Conditions:
  HasLogForwarding: !Equals [!Ref LogForwarding, "True"]
  HasLogInvocation: !Equals [!Ref LogInvocation, "True"]
  HasScheduleExpression: !Not [!Equals [!Ref ScheduleExpression, ""]]

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "restyled-${FunctionName}"
      Runtime: !Ref FunctionRuntime
      Code:
        S3Bucket: !Ref FunctionSourceBucket
        S3Key: !Ref FunctionSourceKey
      Handler: !Ref FunctionHandler
      Timeout: !Ref FunctionTimeout
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/restyled-${FunctionRole}"

  LogGroup:
    Condition: HasLogForwarding
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 7

  LogGroupSubscription:
    Condition: HasLogForwarding
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:restyled-forward-logs"
      LogGroupName: !Ref LogGroup
      FilterPattern: "-START -END -REPORT"

  LambdaScheduleRule:
    Condition: HasScheduleExpression
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub "Trigger restyled-${LambdaFunction}"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Id: !Ref LambdaFunction
          Arn: !GetAtt LambdaFunction.Arn

  LambdaInvokePermission:
    Condition: HasLogInvocation
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: !Sub "logs.${AWS::Region}.amazonaws.com"
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"

  LambdaSchedulePermission:
    Condition: HasScheduleExpression
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleRule.Arn
