#!/usr/bin/env python
import json
import main
import time

from pygments import highlight
from pygments.lexers import JsonLexer
from pygments.formatters import TerminalFormatter

result = main.handler(None, None)
highlighted = highlight(
    json.dumps(result, indent=2),
    JsonLexer(),
    TerminalFormatter()
)

print(highlighted)
