#!/usr/bin/env bash
set -eou pipefail

dir=$(cd "$(dirname "$0")" && pwd)
cd "$dir"

# shellcheck disable=SC1090
source .venv/bin/activate

export ENV=prod

while true; do
  echo "[$(pwd | sed "s|^$HOME|~|")]$ ENV=$ENV ./run"
  ./run
  sleep 30
done
