Parameters:
  Environment:
    Type: String
  QueueDepthThreshold:
    Type: Number
  QueueDepthPeriod:
    Type: Number
  UnknownFailuresThreshold:
    Type: Number
  UnknownFailuresPeriod:
    Type: Number

Resources:
  AlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "RestyledAlarmsTopic-${Environment}"
      Subscription:
        - Protocol: email
          Endpoint: alarms@restyled.io

  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Queue is at Alert threshold"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: !Ref Environment
      EvaluationPeriods: 2
      MetricName: QueueDepth
      Namespace: Restyled
      Period: !Ref QueueDepthPeriod
      Statistic: Minimum
      Threshold: !Ref QueueAlertThreshold
      TreatMissingData: breaching
      Unit: Count

  UnknownFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmsTopic
      OKActions:
        - !Ref AlarmsTopic
      AlarmDescription: !Sub "Restyled ${Environment} Unknown Failures"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: Environment
          Value: !Ref Environment
      EvaluationPeriods: 1
      MetricName: JobsFailedUnknown
      Namespace: Restyled
      Period: !Ref UnknownFailuresPeriod
      Statistic: Minimum
      Threshold: !Ref UnknownFailuresThreshold
      TreatMissingData: breaching
      Unit: Count
