name: CI

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install cfn-lint
      - run: cfn-lint

  sync:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [validate]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: restyled-io/aws-s3-sync-by-hash-action@v1
        with:
          root: cg-app
          bucket: cg-app-cfstack-bucket
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: us-east-1
