name: Deploy cg-app

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: aws-sync
      - run: ./aws-sync/sync cg-app cg-app-cfstack-bucket
